const userModel = require('../models/userModel');
const groupModel = require('../models/groupModel');
const treasuryModel = require('../models/treasuryModel');
const { safeTelegram } = require('../utils/telegram');
const { escHtml } = require('../utils/format');
const { sleep } = require('../utils/helpers');
let current = null;
async function startBroadcast(bot, ownerChatId, text, progressCb){ if(current&&!current.cancelled) throw new Error('BROADCAST_RUNNING'); const runId=`${Date.now()}_${Math.random().toString(36).slice(2,8)}`; current={id:runId,cancelled:false}; await treasuryModel.collection().updateOne({key:'treasury'},{$set:{broadcastRunning:true,broadcastRunId:runId,updatedAt:new Date()}}); const seen=new Set(), targets=[]; for(const u of await userModel.collection().find({}, {projection:{userId:1}}).toArray()){ const id=Number(u.userId); if(Number.isFinite(id)&&!seen.has(id)){seen.add(id);targets.push({chatId:id,kind:'user'});} } for(const g of await groupModel.collection().find({approvalStatus:'approved'}, {projection:{groupId:1}}).toArray()){ const id=Number(g.groupId); if(Number.isFinite(id)&&!seen.has(id)){seen.add(id);targets.push({chatId:id,kind:'group'});} } let ok=0,fail=0,skipped=0,userSent=0,groupSent=0; for(let i=0;i<targets.length;i++){ if(!current||current.id!==runId||current.cancelled) break; const t=targets[i]; try{ await safeTelegram(()=>bot.telegram.sendMessage(t.chatId,`📣 <b>BIKA Broadcast</b>\n━━━━━━━━━━━━━━\n${escHtml(text)}`,{parse_mode:'HTML',disable_web_page_preview:true}),{maxRetries:2}); ok++; if(t.kind==='user')userSent++; else groupSent++; }catch(e){ const m=String(e?.message||e).toLowerCase(); if(m.includes('forbidden')||m.includes('blocked')||m.includes('chat not found')||m.includes('kicked')) skipped++; else fail++; } if((i+1)%25===0 && progressCb) await progressCb({runId,processed:i+1,total:targets.length,ok,fail,skipped,userSent,groupSent}); await sleep(20); } current=null; await treasuryModel.collection().updateOne({key:'treasury'},{$set:{broadcastRunning:false,broadcastRunId:null,updatedAt:new Date()}}); return {ok,fail,skipped,userSent,groupSent}; }
function stopBroadcast(){ if(current){ current.cancelled=true; return true; } return false; }
module.exports = { startBroadcast, stopBroadcast };
