const userModel = require('../models/userModel');
const treasuryModel = require('../models/treasuryModel');
const { withMaybeTx } = require('../config/database');
const { toNum } = require('../utils/format');
const { logTx } = require('./transactionService');
function extract(res){ return res?.value !== undefined ? res.value : res; }
async function getUser(userId){ return userModel.collection().findOne({ userId }); }
async function getUserByUsername(username){ return userModel.collection().findOne({ username: String(username).toLowerCase() }); }
async function ensureUser(tgUser){ const now=new Date(); const userId=tgUser.id || tgUser.userId; const doc={ userId, username: tgUser.username?String(tgUser.username).toLowerCase():null, firstName: tgUser.first_name || tgUser.firstName || null, lastName: tgUser.last_name || tgUser.lastName || null, updatedAt: now }; await userModel.collection().updateOne({userId},{$set:doc,$setOnInsert:{balance:0,totalWon:0,totalLost:0,createdAt:now,startBonusClaimed:false,lastDailyClaimAt:null,isVip:false,startedBot:false}},{upsert:true}); return getUser(userId); }
async function markStarted(userId){ await userModel.collection().updateOne({userId},{$set:{startedBot:true,updatedAt:new Date()}}); }
async function treasuryPayToUser(toUserId, amount, meta={}){ const amt=Math.floor(toNum(amount)); if(amt<=0)return; return withMaybeTx(async(session)=>{ const opts=session?{session,returnDocument:'after'}:{returnDocument:'after'}; const t=extract(await treasuryModel.collection().findOneAndUpdate({key:'treasury',ownerBalance:{$gte:amt}},{$inc:{ownerBalance:-amt},$set:{updatedAt:new Date()}},opts)); if(!t) throw new Error('TREASURY_INSUFFICIENT'); const uopts=session?{session,upsert:true}:{upsert:true}; await userModel.collection().updateOne({userId:toUserId},{$inc:{balance:amt,totalWon: meta.type?.includes('win')?amt:0},$set:{updatedAt:new Date()},$setOnInsert:{createdAt:new Date()}},uopts); await logTx({type:meta.type||'treasury_pay',fromUserId:'TREASURY',toUserId,amount:amt,meta},{session}); }); }
async function userPayToTreasury(fromUserId, amount, meta={}){ const amt=Math.floor(toNum(amount)); if(amt<=0)return; return withMaybeTx(async(session)=>{ const opts=session?{session,returnDocument:'after'}:{returnDocument:'after'}; const u=extract(await userModel.collection().findOneAndUpdate({userId:fromUserId,balance:{$gte:amt}},{$inc:{balance:-amt,totalLost: meta.type?.includes('bet')?amt:0},$set:{updatedAt:new Date()}},opts)); if(!u) throw new Error('USER_INSUFFICIENT'); const topts=session?{session}:{ }; await treasuryModel.collection().updateOne({key:'treasury'},{$inc:{ownerBalance:amt},$set:{updatedAt:new Date()}},topts); await logTx({type:meta.type||'treasury_receive',fromUserId,toUserId:'TREASURY',amount:amt,meta},{session}); }); }
async function transferBalance(fromUserId,toUserId,amount,meta={}){ const amt=Math.floor(toNum(amount)); if(amt<=0)return; return withMaybeTx(async(session)=>{ const opts=session?{session,returnDocument:'after'}:{returnDocument:'after'}; const u=extract(await userModel.collection().findOneAndUpdate({userId:fromUserId,balance:{$gte:amt}},{$inc:{balance:-amt},$set:{updatedAt:new Date()}},opts)); if(!u) throw new Error('INSUFFICIENT'); await userModel.collection().updateOne({userId:toUserId},{$inc:{balance:amt},$set:{updatedAt:new Date()},$setOnInsert:{createdAt:new Date()}},session?{session,upsert:true}:{upsert:true}); await logTx({type:'gift',fromUserId,toUserId,amount:amt,meta},{session}); }); }
module.exports = { ensureUser, markStarted, getUser, getUserByUsername, treasuryPayToUser, userPayToTreasury, transferBalance };
