'use strict';
const crypto = require('crypto');
const { getUser, transferBalance } = require('./economyService');
const { toNum } = require('../utils/format');
const userModel = require('../models/userModel');
const ALPHABET = 'abcdefghijklmnopqrstuvwxyz';
function randomSuffix(){const bytes=crypto.randomBytes(5);let out='';for(let i=0;i<5;i++)out+=ALPHABET[bytes[i]%26];return out;}
function walletIdForUserId(userId,suffix){const raw=String(userId||'').trim();if(!/^\d+$/.test(raw))return null;const tail=String(suffix||'').toLowerCase();if(!/^[a-z]{5}$/.test(tail))return null;return `Bika${raw}${tail}`;}
function userIdFromWalletId(walletId){const value=String(walletId||'').trim();const m=/^Bika(\d+)([a-z]{5})$/i.exec(value);return m?m[1]:null;}
async function ensureWalletId(userId){const existing=await getUser(userId);if(!existing)throw new Error('USER_NOT_FOUND');if(existing.walletId&&/^Bika\d+[a-z]{5}$/i.test(existing.walletId))return String(existing.walletId);for(let i=0;i<5;i++){const candidate=walletIdForUserId(existing.userId,randomSuffix());const result=await userModel.collection().updateOne({userId:existing.userId,walletId:{$exists:false}},{$set:{walletId:candidate,updatedAt:new Date()}});if(result.matchedCount===1||result.modifiedCount===1)return candidate;const fresh=await getUser(userId);if(fresh?.walletId)return String(fresh.walletId);}throw new Error('WALLET_CREATE_FAILED');}
function maskWalletId(walletId){const v=String(walletId||'');return v.length<=8?'••••••••':`${v.slice(0,5)}••••••${v.slice(-3)}`;}
async function findWalletOwner(walletId){const value=String(walletId||'').trim();if(!value)throw new Error('WALLET_INVALID');const escaped=value.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&');const direct=await userModel.collection().findOne({walletId:new RegExp(`^${escaped}$`,'i')});if(direct)return direct;const userId=userIdFromWalletId(value);if(!userId)throw new Error('WALLET_INVALID');const legacy=await getUser(userId);if(!legacy)throw new Error('WALLET_NOT_FOUND');const canonical=await ensureWalletId(legacy.userId);if(String(canonical).toLowerCase()!==value.toLowerCase())throw new Error('WALLET_INVALID');return await getUser(legacy.userId);}
async function getWallet(userId){const u=await getUser(userId);if(!u)throw new Error('USER_NOT_FOUND');const walletId=await ensureWalletId(u.userId);const fresh=await getUser(u.userId);return {walletId,maskedWalletId:maskWalletId(walletId),balance:Number(fresh?.balance||0),userId:fresh.userId,firstName:fresh.firstName||null,lastName:fresh.lastName||null,username:fresh.username||null,photoUrl:fresh.photoUrl||null};}
async function lookupWallet(walletId){const u=await findWalletOwner(walletId);const canonical=await ensureWalletId(u.userId);return {walletId:canonical,userId:u.userId,firstName:u.firstName||null,lastName:u.lastName||null,username:u.username||null,photoUrl:u.photoUrl||null};}
async function transferByWallet(fromUserId,recipientWalletId,amount){const amt=Math.floor(toNum(amount));if(!Number.isFinite(amt)||amt<=0)throw new Error('INVALID_TRANSFER_AMOUNT');const recipient=await findWalletOwner(recipientWalletId);const toUserId=String(recipient.userId);if(String(fromUserId)===toUserId)throw new Error('TRANSFER_SELF');const canonical=await ensureWalletId(toUserId);await transferBalance(fromUserId,toUserId,amt,{source:'mini_wallet',recipientWalletId:canonical});const sender=await getUser(fromUserId);return {amount:amt,walletId:canonical,senderBalance:Number(sender?.balance||0)};}
module.exports={walletIdForUserId,userIdFromWalletId,maskWalletId,getWallet,lookupWallet,transferByWallet};
