'use strict';
const { BLACKJACK = {} } = require('../config/constants');
const { getUser, userPayToTreasury, treasuryPayToUser } = require('./economyService');
const { getWebGameRtp, setWebGameRtp } = require('./webGameRtpService');
const { recordWebGameHistory } = require('./webBetHistoryService');
const MIN_BET=Math.max(1,Number(process.env.WEB_BJ_MIN_BET||BLACKJACK.minBet||50));
const MAX_BET=Math.max(MIN_BET,Number(process.env.WEB_BJ_MAX_BET||BLACKJACK.maxBet||10000));
const MAX_PLAYERS=Math.max(2,Math.min(5,Number(process.env.WEB_BJ_MAX_PLAYERS||5)));
const JOIN_SECONDS=Math.max(15,Number(process.env.WEB_BJ_JOIN_SECONDS||45));
const ACTION_SECONDS=Math.max(30,Number(process.env.WEB_BJ_ACTION_SECONDS||90));
const NEXT_ROUND_SECONDS=Math.max(2,Number(process.env.WEB_BJ_NEXT_ROUND_SECONDS||5));
const ROOM_TTL_MS=Math.max(5*60_000,Number(process.env.WEB_BJ_ROOM_TTL_MS||15*60_000));
const RTP_GAME_KEY='blackjack';
const RANKS=Object.freeze(['A','2','3','4','5','6','7','8','9','10','J','Q','K']);
const SUITS=Object.freeze(['♠','♥','♦','♣']);
const rooms=new Map();
const nowMs=()=>Date.now();
const makeRoomId=()=>`wbj_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const cleanRoomId=v=>String(v||'').trim().replace(/[^A-Za-z0-9_-]/g,'').slice(0,48);
const safeBet=v=>{const n=Number(v);return Number.isFinite(n)?Math.floor(n):0;};
const playerName=u=>[u.first_name||u.firstName,u.last_name||u.lastName].filter(Boolean).join(' ').trim()||u.username||`Player ${String(u.id||'').slice(-4)}`;
const avatarText=n=>String(n||'BJ').replace(/[^A-Za-z0-9]/g,'').slice(0,2).toUpperCase()||'BJ';
function createDeck(){const d=[];for(const s of SUITS)for(const r of RANKS)d.push({rank:r,suit:s});for(let i=d.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]];}return d;}
function draw(r){if(!r.deck?.length)r.deck=createDeck();return r.deck.pop();}
const makeCard=(rank,suit='♠')=>({rank:String(rank),suit});
function cardValue(c){if(c.rank==='A')return 11;if(['K','Q','J'].includes(c.rank))return 10;return Number(c.rank)||0;}
function handValue(cards=[]){let t=0,a=0;for(const c of cards){t+=cardValue(c);if(c.rank==='A')a++;}while(t>21&&a>0){t-=10;a--;}return t;}
const isNatural=c=>c.length===2&&handValue(c)===21;
function handForTotal(total){const v=Math.max(17,Math.min(21,Math.floor(Number(total)||17)));if(v===21)return[makeCard('A','♠'),makeCard('K','♥')];if(v===20)return[makeCard('K','♠'),makeCard('Q','♥')];if(v===19)return[makeCard('10','♠'),makeCard('9','♥')];if(v===18)return[makeCard('10','♠'),makeCard('8','♥')];return[makeCard('10','♠'),makeCard('7','♥')];}
const bustHand=()=>[makeCard('K','♠'),makeCard('8','♥'),makeCard('6','♦')];
function decideResult(p,d){const pv=handValue(p.hand),dv=handValue(d),pn=isNatural(p.hand),dn=isNatural(d);if(pn&&dn)return'PUSH';if(pn)return'BLACKJACK';if(dn)return'LOSE';if(pv>21)return'LOSE';if(dv>21)return'WIN';if(pv>dv)return'WIN';if(pv<dv)return'LOSE';return'PUSH';}
const payoutFor=(r,b)=>r==='BLACKJACK'?Math.floor(b*2.5):r==='WIN'?b*2:r==='PUSH'?b:0;
const finalActionDone=p=>['stand','bust','blackjack','settled','left'].includes(p.status);
function cleanupRooms(){const cut=nowMs()-ROOM_TTL_MS;for(const[id,r]of rooms){if(r.finishedAtMs&&r.finishedAtMs<cut)rooms.delete(id);else if(r.createdAtMs<cut&&['lobby','expired'].includes(r.state)&&r.players.size===0)rooms.delete(id);}}
function getRoomOrThrow(id){cleanupRooms();const r=rooms.get(cleanRoomId(id));if(!r)throw new Error('BJ_ROOM_NOT_FOUND');return r;}
const getWebBlackjackRtp=()=>getWebGameRtp(RTP_GAME_KEY);
const setWebBlackjackRtp=(v,u=null)=>setWebGameRtp(RTP_GAME_KEY,v,u);
function resetRoundForLobby(r){if(!r||r.state!=='finished')return r;r.state='lobby';r.settled=false;r.deck=[];r.dealer=[];r.actionDeadlineMs=null;r.finishedAtMs=null;r.createdAtMs=nowMs();r.joinDeadlineMs=nowMs()+JOIN_SECONDS*1000;r.nextRoundAtMs=null;r.roundNo=Number(r.roundNo||0)+1;r.players.clear();return r;}
function scheduleNextRound(r){if(r.nextRoundTimer)clearTimeout(r.nextRoundTimer);r.nextRoundAtMs=nowMs()+NEXT_ROUND_SECONDS*1000;r.nextRoundTimer=setTimeout(()=>{r.nextRoundTimer=null;if(r.state==='finished')resetRoundForLobby(r);},NEXT_ROUND_SECONDS*1000);}
async function createWebBlackjackRoom({chatId,title='',createdBy=null}={}){cleanupRooms();const r={id:makeRoomId(),chatId:chatId||null,title:String(title||'Bika Blackjack Table').slice(0,80),createdBy,createdAtMs:nowMs(),joinDeadlineMs:nowMs()+JOIN_SECONDS*1000,actionDeadlineMs:null,nextRoundAtMs:null,nextRoundTimer:null,state:'lobby',deck:[],dealer:[],players:new Map(),rtp:await getWebBlackjackRtp(),settled:false,roundNo:1};rooms.set(r.id,r);return publicRoom(r,createdBy);}
function maybeAutoStartOrExpire(r){if(r.state==='finished'&&r.nextRoundAtMs&&nowMs()>=r.nextRoundAtMs)resetRoundForLobby(r);if(r.state==='lobby'&&nowMs()>=r.joinDeadlineMs){if(r.players.size)startRound(r);else{r.state='expired';r.finishedAtMs=nowMs();}}if(r.state==='playing'&&r.actionDeadlineMs&&nowMs()>=r.actionDeadlineMs){for(const p of r.players.values())if(p.status==='playing')p.status='stand';return finishDealer(r).catch(e=>console.error('WEB_BJ_AUTO_FINISH_FAILED:',e?.message||e));}return null;}
function startRound(r){if(r.state!=='lobby')return r;if(!r.players.size){r.state='expired';r.finishedAtMs=nowMs();return r;}r.deck=createDeck();r.dealer=[];for(const p of r.players.values()){p.hand=[];p.result=null;p.payout=0;p.net=-p.bet;p.status='playing';}for(let i=0;i<2;i++){for(const p of r.players.values())p.hand.push(draw(r));r.dealer.push(draw(r));}for(const p of r.players.values())if(isNatural(p.hand))p.status='blackjack';r.state='playing';r.actionDeadlineMs=nowMs()+ACTION_SECONDS*1000;if([...r.players.values()].every(finalActionDone))finishDealer(r).catch(e=>console.error('WEB_BJ_NATURAL_FINISH_FAILED:',e?.message||e));return r;}
function shapeDealerForTable(r){const totals=[...r.players.values()].map(p=>handValue(p.hand)).filter(v=>v<=21);if(!totals.length)return handForTotal(18);const rtp=Math.max(40,Math.min(95,Number(r.rtp||65)));if(Math.random()*100<rtp){if(Math.random()<.72)return bustHand();const min=Math.min(...totals);return handForTotal(Math.max(17,Math.min(20,min-1)));}const max=Math.max(...totals);return handForTotal(Math.max(17,Math.min(21,max+1)));}
async function finishDealer(r){if(!r||r.settled||!['playing','dealer'].includes(r.state))return r;r.state='dealer';r.dealer=shapeDealerForTable(r);while(handValue(r.dealer)<17)r.dealer.push(draw(r));for(const p of r.players.values()){const result=decideResult(p,r.dealer),payout=payoutFor(result,p.bet);p.result=result;p.payout=payout;p.net=payout-p.bet;p.status='settled';if(payout>0){try{await treasuryPayToUser(p.userId,payout,{type:'web_blackjack_payout',bet:p.bet,payout,result,roomId:r.id,rtp:r.rtp});}catch(e){console.error('WEB_BJ_PAYOUT_FAILED:',e?.message||e);p.result='PAYOUT_ERROR';p.payout=0;p.net=-p.bet;}}await recordWebGameHistory({userId:p.userId,game:'blackjack',title:'Web Blackjack',outcome:p.result,bet:p.bet,payout:p.payout,net:p.net,label:p.result==='BLACKJACK'?'Blackjack':p.result,meta:{roomId:r.id,playerTotal:handValue(p.hand),dealerTotal:handValue(r.dealer),players:r.players.size}});}r.state='finished';r.settled=true;r.finishedAtMs=nowMs();scheduleNextRound(r);return r;}
async function joinWebBlackjack({roomId,userId,user={},bet}={}){const r=getRoomOrThrow(roomId);maybeAutoStartOrExpire(r);if(r.state!=='lobby'){if(r.state==='finished'){const e=new Error('BJ_NEXT_ROUND_WAIT');e.nextAtMs=r.nextRoundAtMs;throw e;}throw new Error(r.state==='expired'?'BJ_ROOM_EXPIRED':'BJ_ALREADY_STARTED');}const uid=Number(userId);if(!Number.isFinite(uid)||uid<=0)throw new Error('INVALID_USER');if(r.players.has(uid))return publicRoom(r,uid);if(r.players.size>=MAX_PLAYERS)throw new Error('BJ_TABLE_FULL');const b=safeBet(bet);if(b<MIN_BET||b>MAX_BET){const e=new Error('BET_RANGE');e.minBet=MIN_BET;e.maxBet=MAX_BET;throw e;}const doc=await getUser(uid);if(Number(doc?.balance||0)<b)throw new Error('USER_INSUFFICIENT');await userPayToTreasury(uid,b,{type:'web_blackjack_bet',roomId:r.id,playerCount:r.players.size+1});const name=playerName({...user,id:uid});r.players.set(uid,{userId:uid,name,avatar:avatarText(name),username:user.username||null,bet:b,hand:[],status:'waiting',result:null,payout:0,net:-b,joinedAtMs:nowMs()});if(r.players.size>=MAX_PLAYERS)startRound(r);return publicRoom(r,uid,await currentBalance(uid));}
async function leaveWebBlackjack({roomId,userId}={}){const r=getRoomOrThrow(roomId),uid=Number(userId),p=r.players.get(uid);if(!p)return publicRoom(r,uid,await currentBalance(uid));if(r.state==='playing'){if(p.status==='playing')p.status='left';p.left=true;if([...r.players.values()].every(finalActionDone))await finishDealer(r);}else{r.players.delete(uid);if(r.state==='lobby'&&!r.players.size)r.joinDeadlineMs=nowMs()+JOIN_SECONDS*1000;}return publicRoom(r,uid,await currentBalance(uid));}
async function hitWebBlackjack({roomId,userId}={}){const r=getRoomOrThrow(roomId);maybeAutoStartOrExpire(r);const p=r.players.get(Number(userId));if(!p)throw new Error('BJ_NOT_JOINED');if(r.state!=='playing')throw new Error('BJ_NOT_PLAYING');if(p.status!=='playing')throw new Error('BJ_ACTION_DONE');p.hand.push(draw(r));const v=handValue(p.hand);if(v>21)p.status='bust';else if(v===21)p.status='stand';if([...r.players.values()].every(finalActionDone))await finishDealer(r);return publicRoom(r,userId,await currentBalance(userId));}
async function standWebBlackjack({roomId,userId}={}){const r=getRoomOrThrow(roomId);maybeAutoStartOrExpire(r);const p=r.players.get(Number(userId));if(!p)throw new Error('BJ_NOT_JOINED');if(r.state!=='playing')throw new Error('BJ_NOT_PLAYING');if(p.status!=='playing')throw new Error('BJ_ACTION_DONE');p.status='stand';if([...r.players.values()].every(finalActionDone))await finishDealer(r);return publicRoom(r,userId,await currentBalance(userId));}
async function currentBalance(uid){try{const u=await getUser(Number(uid));return Number(u?.balance||0);}catch(_){return 0;}}
async function getWebBlackjackStatus({roomId,userId}={}){const r=getRoomOrThrow(roomId);const a=maybeAutoStartOrExpire(r);if(a&&typeof a.then==='function')await a;return publicRoom(r,userId,await currentBalance(userId));}
function publicCard(c){if(!c)return{hidden:true};return{rank:c.rank,suit:c.suit,red:['♥','♦'].includes(c.suit)};}
function publicPlayer(p,viewerId){const me=Number(p.userId)===Number(viewerId);return{userId:p.userId,name:p.name,avatar:p.avatar,me,bet:p.bet,status:p.status,result:p.result,payout:p.payout,net:p.net,total:me?handValue(p.hand):null,cards:me?p.hand.map(publicCard):p.hand.map(()=>({hidden:true}))};}
function publicRoom(r,viewerId=null,balance=null){const reveal=['dealer','finished'].includes(r.state);const players=[...r.players.values()].map(p=>publicPlayer(p,viewerId));const me=players.find(p=>p.me)||null;return{ok:true,room:{id:r.id,title:r.title,state:r.state,maxPlayers:MAX_PLAYERS,playerCount:r.players.size,joinSecondsLeft:r.state==='lobby'?Math.max(0,Math.ceil((r.joinDeadlineMs-nowMs())/1000)):0,actionSecondsLeft:r.state==='playing'?Math.max(0,Math.ceil((r.actionDeadlineMs-nowMs())/1000)):0,nextRoundSecondsLeft:r.state==='finished'?Math.max(0,Math.ceil((r.nextRoundAtMs-nowMs())/1000)):0,nextRoundAtMs:r.nextRoundAtMs||null,createdAtMs:r.createdAtMs,dealer:{reveal,total:reveal?handValue(r.dealer):null,cards:reveal?r.dealer.map(publicCard):r.dealer.map(()=>({hidden:true}))},players,me,rtp:r.rtp},balance,config:{minBet:MIN_BET,maxBet:MAX_BET,maxPlayers:MAX_PLAYERS,joinSeconds:JOIN_SECONDS,actionSeconds:ACTION_SECONDS,nextRoundSeconds:NEXT_ROUND_SECONDS}};}
module.exports={createWebBlackjackRoom,joinWebBlackjack,leaveWebBlackjack,getWebBlackjackStatus,hitWebBlackjack,standWebBlackjack,getWebBlackjackRtp,setWebBlackjackRtp,MIN_BET,MAX_BET,MAX_PLAYERS,JOIN_SECONDS,ACTION_SECONDS,NEXT_ROUND_SECONDS};
