'use strict';
const { publicMiniAppUrl } = require('../../web/miniAppRoutes');
const { getBotInfo } = require('../../config/bot');
const { replyHTML } = require('../../utils/telegram');
const { ensureTreasury, isOwner } = require('../../services/treasuryService');
const { getRocketRtp, setRocketRtp } = require('../../services/webCrashService');
const { cleanGameKey, getWebGameRtp, setWebGameRtp, getAllWebGameRtps, gameLabel } = require('../../services/webGameRtpService');
const { createWebBlackjackRoom } = require('../../services/webBlackjackService');
const { createWebShanRoom } = require('../../services/webShanService');
const { ensureUser } = require('../../services/economyService');
const { setBackgroundMusic, clearBackgroundMusic } = require('../../services/backgroundMusicService');
function appKeyboard(url){return {inline_keyboard:[[{text:'🎮 Open Bika Game App',web_app:{url}}]]};}
function miniAppDirectLink(startParam=''){const username=getBotInfo()?.username||process.env.BOT_USERNAME||'';if(!username)return null;const clean=String(username).replace(/^@/,'');const suffix=startParam?`?startapp=${encodeURIComponent(startParam)}`:'?startapp';return `https://t.me/${clean}${suffix}`;}
function miniAppJoinKeyboard(ctx,webUrl,label,startParam){const isPrivate=ctx.chat?.type==='private';const directUrl=miniAppDirectLink(startParam);if(isPrivate)return {inline_keyboard:[[{text:label,web_app:{url:webUrl}}]]};return {inline_keyboard:[[{text:label,url:directUrl||webUrl}]]};}
function replyOptions(ctx){const messageId=ctx.message?.message_id;return messageId?{reply_to_message_id:messageId,allow_sending_without_reply:true}:{};}
function isPrivateChat(ctx){return ctx.chat?.type==='private';}
function parsePercent(text){const parts=String(text||'').trim().split(/\s+/);const raw=String(parts[1]||'').replace('%','').trim();const n=Number(raw);return Number.isFinite(n)?Math.floor(n):null;}
function parseAmountArg(text,fallback=5000){const parts=String(text||'').trim().split(/\s+/);const raw=String(parts[1]||'').replace(/,/g,'').trim();const n=Number(raw);return Number.isFinite(n)&&n>0?Math.floor(n):fallback;}
function parseSetGameRtp(text){const parts=String(text||'').trim().split(/\s+/);const game=cleanGameKey(parts[1]);const raw=String(parts[2]||'').replace('%','').trim();const n=Number(raw);return {game,value:Number.isFinite(n)?Math.floor(n):null};}
function setCommandFor(gameKey){const key=cleanGameKey(gameKey);if(key==='rocket')return '/setrocketrtp 70';if(key==='blackjack')return '/setwebbjrtp 70';if(key==='shan')return '/setwebshanrtp 70';if(key==='mines')return '/setwebminesrtp 70';return `/set${key}rtp 70`;}
async function requireOwnerDm(ctx){const treasury=await ensureTreasury();if(!isOwner(ctx,treasury)){await replyHTML(ctx,'⛔ Owner only.',replyOptions(ctx));return false;}if(!isPrivateChat(ctx)){await replyHTML(ctx,'ℹ️ Web game RTP command ကို bot DM ထဲမှာပဲသုံးပါ။',replyOptions(ctx));return false;}return true;}
async function showSingleRtp(ctx,game){const key=cleanGameKey(game);const rtp=key==='rocket'?await getRocketRtp():await getWebGameRtp(key);const setCmd=setCommandFor(key);return replyHTML(ctx,`🎛 <b>Web ${gameLabel(key)} RTP</b>\n━━━━━━━━━━━━━━━━\nCurrent RTP: <b>${rtp}%</b>\n\nပြင်ရန်: <code>${setCmd}</code>\nRange: <b>40% - 95%</b>\n\n<i>RTP နည်းလေ owner safe ပိုဖြစ်ပြီး game ပိုတင်းပါတယ်။</i>`,replyOptions(ctx));}
async function setSingleRtp(ctx,game,value){const key=cleanGameKey(game);if(value==null||value<40||value>95)return replyHTML(ctx,`Usage: <code>${setCommandFor(key)}</code>\nRange: <b>40% - 95%</b>`,replyOptions(ctx));const rtp=key==='rocket'?await setRocketRtp(value,ctx.from?.id):await setWebGameRtp(key,value,ctx.from?.id);return replyHTML(ctx,`✅ <b>Web ${gameLabel(key)} RTP Updated</b>\n━━━━━━━━━━━━━━━━\nNew RTP: <b>${rtp}%</b>\n\nပိုတင်းချင်ရင်: <code>${setCommandFor(key).replace('70','60')}</code>\nပိုပေးချင်ရင်: <code>${setCommandFor(key).replace('70','80')}</code>`,replyOptions(ctx));}
module.exports=(bot)=>{
 bot.command(['app','web','miniapp'],async(ctx)=>{const url=publicMiniAppUrl();if(!url||url==='/miniapp')return replyHTML(ctx,'⚠️ Mini App URL မသတ်မှတ်ရသေးပါ။ Render မှာ <code>PUBLIC_URL</code> ကို သင့် service URL နဲ့ထည့်ပါ။',replyOptions(ctx));return replyHTML(ctx,'🎮 <b>Bika Game Mini App</b>\n━━━━━━━━━━━━━━━━\nWeb ထဲမှာ Rocket / Slot / Blackjack / Shan Koe Mee / Plinko / Wheel / Mines ဆော့နိုင်ပါတယ်။\n\nအောက်က button ကိုနှိပ်ပါ။',{...replyOptions(ctx),reply_markup:miniAppJoinKeyboard(ctx,url,'🎮 Open Bika Game App','web')});});
 bot.command('setbgmusic',async(ctx)=>{const treasury=await ensureTreasury();if(!isOwner(ctx,treasury))return replyHTML(ctx,'⛔ Owner only.',replyOptions(ctx));if(!isPrivateChat(ctx))return replyHTML(ctx,'ℹ️ /setbgmusic ကို bot DM ထဲမှာပဲသုံးပါ။',replyOptions(ctx));const replied=ctx.message?.reply_to_message;const audio=replied?.audio||null;const document=replied?.document||null;const mime=audio?.mime_type||document?.mime_type||'';const fileId=audio?.file_id||(String(mime).startsWith('audio/')?document?.file_id:null);if(!fileId)return replyHTML(ctx,'🎵 <b>Usage</b>\n\n1. Bot DM မှာ audio file ပို့ပါ။\n2. အဲဒီ audio ကို reply ထောက်ပါ။\n3. <code>/setbgmusic</code> ပို့ပါ။\n\nAudio file သို့မဟုတ် audio/* document ကို support လုပ်ပါတယ်။',replyOptions(ctx));await setBackgroundMusic({fileId,title:audio?.title||audio?.file_name||document?.file_name||'Bika Premium Arena',mimeType:mime||'audio/mpeg',ownerId:ctx.from?.id});return replyHTML(ctx,'✅ <b>Background Music Updated</b>\n\nဒီ audio ကို Bika Premium Arena Mini App ရဲ့ background music အဖြစ် သတ်မှတ်ထားပါတယ်။\n\n🎵 Mini App ကို reopen လုပ်ပြီး Sound On နှိပ်ပါ။',replyOptions(ctx));});
 bot.command('clearbgmusic',async(ctx)=>{const treasury=await ensureTreasury();if(!isOwner(ctx,treasury))return replyHTML(ctx,'⛔ Owner only.',replyOptions(ctx));if(!isPrivateChat(ctx))return replyHTML(ctx,'ℹ️ /clearbgmusic ကို bot DM ထဲမှာပဲသုံးပါ။',replyOptions(ctx));await clearBackgroundMusic();return replyHTML(ctx,'✅ Background music ဖယ်ရှားပြီးပါပြီ။',replyOptions(ctx));});
 bot.command(['webgamertp','webgamesrtp'],async(ctx)=>{if(!(await requireOwnerDm(ctx)))return;const rtps=await getAllWebGameRtps();rtps.rocket=await getRocketRtp();const lines=['rocket','blackjack','shan','plinko','wheel','mines'].map(key=>`• <b>${gameLabel(key)}</b>: <b>${rtps[key]}%</b>`).join('\n');return replyHTML(ctx,`🎛 <b>Web Game RTP Control</b>\n━━━━━━━━━━━━━━━━\n${lines}\n\nCommands:\n<code>/setrocketrtp 70</code>\n<code>/setwebbjrtp 70</code>\n<code>/setwebshanrtp 70</code>\n<code>/setplinkortp 70</code>\n<code>/setwheelrtp 70</code>\n<code>/setwebminesrtp 70</code>\n\nGeneral: <code>/setwebgamertp plinko 70</code>`,replyOptions(ctx));});
 bot.command(['rocketrtp','webcrashrtp'],async(ctx)=>{if(!(await requireOwnerDm(ctx)))return;return showSingleRtp(ctx,'rocket');});bot.command(['webbjrtp','webblackjackrtp','bjwebrtp'],async(ctx)=>{if(!(await requireOwnerDm(ctx)))return;return showSingleRtp(ctx,'blackjack');});bot.command(['webshanrtp','shankoemeertp','shanrtp'],async(ctx)=>{if(!(await requireOwnerDm(ctx)))return;return showSingleRtp(ctx,'shan');});bot.command(['plinkortp'],async(ctx)=>{if(!(await requireOwnerDm(ctx)))return;return showSingleRtp(ctx,'plinko');});bot.command(['wheelrtp','luckywheelrtp'],async(ctx)=>{if(!(await requireOwnerDm(ctx)))return;return showSingleRtp(ctx,'wheel');});bot.command(['webminesrtp','mineswebrtp'],async(ctx)=>{if(!(await requireOwnerDm(ctx)))return;return showSingleRtp(ctx,'mines');});bot.command(['setrocketrtp','setwebcrashrtp'],async(ctx)=>{if(!(await requireOwnerDm(ctx)))return;return setSingleRtp(ctx,'rocket',parsePercent(ctx.message?.text));});bot.command(['setwebbjrtp','setwebblackjackrtp','setbjwebrtp'],async(ctx)=>{if(!(await requireOwnerDm(ctx)))return;return setSingleRtp(ctx,'blackjack',parsePercent(ctx.message?.text));});bot.command(['setwebshanrtp','setshankoemeertp','setshanrtp'],async(ctx)=>{if(!(await requireOwnerDm(ctx)))return;return setSingleRtp(ctx,'shan',parsePercent(ctx.message?.text));});bot.command(['setplinkortp'],async(ctx)=>{if(!(await requireOwnerDm(ctx)))return;return setSingleRtp(ctx,'plinko',parsePercent(ctx.message?.text));});bot.command(['setwheelrtp','setluckywheelrtp'],async(ctx)=>{if(!(await requireOwnerDm(ctx)))return;return setSingleRtp(ctx,'wheel',parsePercent(ctx.message?.text));});bot.command(['setwebminesrtp','setmineswebrtp'],async(ctx)=>{if(!(await requireOwnerDm(ctx)))return;return setSingleRtp(ctx,'mines',parsePercent(ctx.message?.text));});bot.command(['setwebgamertp'],async(ctx)=>{if(!(await requireOwnerDm(ctx)))return;const parsed=parseSetGameRtp(ctx.message?.text);if(!['rocket','blackjack','shan','plinko','wheel','mines'].includes(parsed.game))return replyHTML(ctx,`Usage: <code>/setwebgamertp plinko 70</code>\nGames: rocket, blackjack, shan, plinko, wheel, mines`,replyOptions(ctx));return setSingleRtp(ctx,parsed.game,parsed.value);});
 bot.hears(/^\.(wbj|webbj|webblackjack)\b/i,async(ctx)=>{if(!['group','supergroup'].includes(ctx.chat?.type))return replyHTML(ctx,'ℹ️ <code>.wbj</code> ကို group ထဲမှာပဲသုံးပါ။',replyOptions(ctx));const baseUrl=publicMiniAppUrl();if(!baseUrl||baseUrl==='/miniapp')return replyHTML(ctx,'⚠️ Mini App URL မသတ်မှတ်ရသေးပါ။ Render မှာ <code>PUBLIC_URL</code> ကို သင့် service URL နဲ့ထည့်ပါ။',replyOptions(ctx));const room=await createWebBlackjackRoom({chatId:ctx.chat?.id,title:ctx.chat?.title||'Bika Blackjack Table',createdBy:ctx.from?.id||null});const url=`${baseUrl}${baseUrl.includes('?')?'&':'?'}game=blackjack&room=${encodeURIComponent(room.room.id)}`;return replyHTML(ctx,'🃏 <b>Web Blackjack Table is open!</b>\n━━━━━━━━━━━━━━━━\nUp to <b>5 players</b> can join this premium Blackjack table.\nOnly your own cards are visible. Other players cannot see your hand.\nDealer cards stay hidden until the dealer turn / final comparison.\n\nTap the button below to join the table.',{...replyOptions(ctx),reply_markup:miniAppJoinKeyboard(ctx,url,'🃏 Join Web Blackjack',`wbj_${room.room.id}`)});});
 bot.hears(/^\.(wshan|webshan|skm)\b/i,async(ctx)=>{const baseUrl=publicMiniAppUrl();if(!baseUrl||baseUrl==='/miniapp')return replyHTML(ctx,'⚠️ Mini App URL မသတ်မှတ်ရသေးပါ။ Render မှာ <code>PUBLIC_URL</code> ကို သင့် service URL နဲ့ထည့်ပါ။',replyOptions(ctx));const bankerStake=parseAmountArg(ctx.message?.text,Number(process.env.WEB_SHAN_DEFAULT_BANKER_STAKE||5000));await ensureUser(ctx.from||{});let room;try{room=await createWebShanRoom({chatId:ctx.chat?.id,title:ctx.chat?.title||'Bika Shan Koe Mee Pro Table',createdBy:ctx.from?.id||null,user:ctx.from||{},bankerStake});}catch(err){const required=err?.required?`\nRequired reserve: <b>${Number(err.required).toLocaleString('en-US')}</b>`:'';return replyHTML(ctx,'⚠️ <b>Cannot open Shan banker table.</b>\nBanker must have enough balance because this is a human-banker table.\nUsage: <code>.wshan 5000</code>'+required,replyOptions(ctx));}const url=`${baseUrl}${baseUrl.includes('?')?'&':'?'}game=shan&room=${encodeURIComponent(room.room.id)}`;return replyHTML(ctx,'🎴 <b>Shan Koe Mee Pro Table is open!</b>\n━━━━━━━━━━━━━━━━\nHuman banker table: players compete against the banker.\n'+`Banker stake: <b>${Number(room.room.banker.stake).toLocaleString('en-US')}</b> • Bet limit: <b>${Number(room.room.betLimit).toLocaleString('en-US')}</b>\n`+'When total bets reach 3x banker stake, the table auto-calls <b>TIN x3</b> and starts dealing.\nDealer moves turn-by-turn from one player to the next.\nOnly your own cards are visible until final reveal.\n\nTap the button below to join the table.',{...replyOptions(ctx),reply_markup:miniAppJoinKeyboard(ctx,url,'🎴 Join Shan Pro Table',`wshan_${room.room.id}`)});});
};
