module.exports = {
  COIN: '$',
  HOUSE_CUT_PERCENT: 0.02,
  START_BONUS: Number(process.env.START_BONUS || 10000),
  DAILY_MIN: Number(process.env.DAILY_MIN || 2000),
  DAILY_MAX: Number(process.env.DAILY_MAX || 5000),
  SLOT: { minBet: 50, maxBet: 7000, cooldownMs: 700, capPercent: 0.30, maxActive: 10 },
  DICE: { minBet: 10, maxBet: 40000, timeoutMs: 60000, maxActive: 5 },
  SHAN: { minBet: 10, maxBet: 100000, timeoutMs: 60000, maxActive: 5 },
  BLACKJACK: { minBet: 50, maxBet: 200000, cooldownMs: 1500 },
  MINES: {
    minBet: Number(process.env.MINES_MIN_BET || 50),
    maxBet: Number(process.env.MINES_MAX_BET || 20000),
    cooldownMs: Number(process.env.MINES_COOLDOWN_MS || 1200),
    actionTimeoutMs: Number(process.env.MINES_ACTION_TIMEOUT_MS || 150000),
    boardSize: 5,
    defaultMines: Number(process.env.MINES_DEFAULT_COUNT || 5),
    minCashoutSafePicks: Number(process.env.MINES_MIN_CASHOUT_SAFE_PICKS || 4),
    allowedMines: [5, 7, 9, 10],
    maxActive: Number(process.env.MINES_MAX_ACTIVE || 30),
    capPercent: Number(process.env.MINES_CAP_PERCENT || 0.10),
    houseEdge: Number(process.env.MINES_HOUSE_EDGE || 0.35),
    firstSafeFreePicks: Number(process.env.MINES_FIRST_SAFE_FREE_PICKS || 1),
    maxPayoutMultiplier: Number(process.env.MINES_MAX_PAYOUT_MULTIPLIER || 5),
    payoutDamping: Number(process.env.MINES_PAYOUT_DAMPING || 0.85),
  },

  CRASH: {
    betSeconds: Number(process.env.CRASH_BET_TIME_SECONDS || 15),
    minBet: Number(process.env.CRASH_MIN_BET || 50),
    maxBet: Number(process.env.CRASH_MAX_BET || 10000),
    editIntervalMs: Number(process.env.CRASH_EDIT_INTERVAL_MS || 900),
    nextRoundDelayMs: Number(process.env.CRASH_NEXT_ROUND_DELAY_MS || 5000),
    maxPlayers: Number(process.env.CRASH_MAX_PLAYERS || 150),
    houseEdge: Number(process.env.CRASH_HOUSE_EDGE || 0.24),
    capPercent: Number(process.env.CRASH_CAP_PERCENT || 0.12),
    maxMultiplier: Number(process.env.CRASH_MAX_MULTIPLIER || 6),
    maxPayoutMultiplier: Number(process.env.CRASH_MAX_PAYOUT_MULTIPLIER || 4),
    instantCrashPercent: Number(process.env.CRASH_INSTANT_PERCENT || 10),
    minVisibleMultiplier: Number(process.env.CRASH_MIN_VISIBLE_MULTIPLIER || 1.16),
    lowCrashMaxMultiplier: Number(process.env.CRASH_LOW_CRASH_MAX_MULTIPLIER || 1.35),
    minCashoutMultiplier: Number(process.env.CRASH_MIN_CASHOUT_MULTIPLIER || 1.10),
    allCashoutHypeMin: Number(process.env.CRASH_ALL_CASHOUT_HYPE_MIN || 25),
    allCashoutHypeMax: Number(process.env.CRASH_ALL_CASHOUT_HYPE_MAX || 250),
    displayPlayerLimit: Number(process.env.CRASH_DISPLAY_PLAYER_LIMIT || 15),
  },
};
