'use strict';
const { ensureUser, getUser } = require('../services/economyService');
const { verifyTelegramMiniAppInitData, getInitDataFromRequest } = require('./telegramMiniAuth');
const { getWallet, lookupWallet, transferByWallet } = require('../services/walletService');
const txModel = require('../models/transactionModel');
function auth(req,res,next){try{const initData=getInitDataFromRequest(req);const a=verifyTelegramMiniAppInitData(initData);req.telegramUser=a.user;return next();}catch(err){const code=String(err?.message||err);const map={MINIAPP_AUTH_MISSING:[401,'Telegram login missing. Open this page from Telegram.'],MINIAPP_AUTH_INVALID:[401,'Telegram login invalid.'],MINIAPP_AUTH_EXPIRED:[401,'Telegram login expired. Please reopen the Mini App.']};const [status,message]=map[code]||[401,'Telegram authentication failed.'];return res.status(status).json({ok:false,error:code,message});}}
function tgUser(u){return {id:u.id,username:u.username||null,first_name:u.first_name||null,last_name:u.last_name||null,language_code:u.language_code||null,is_premium:!!u.is_premium,photo_url:u.photo_url||null};}
function escHtml(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function displayName(u){return [u?.firstName,u?.lastName].filter(Boolean).join(' ').trim()||u?.username||'Bika Player';}
function sendError(res,err){const code=String(err?.message||err);const map={USER_NOT_FOUND:[404,'User data မတွေ့ပါ။ Bot ကို /start အရင်လုပ်ပါ။'],WALLET_INVALID:[400,'Wallet ID မမှန်ပါ။'],WALLET_NOT_FOUND:[404,'ဒီ Wallet ID ပိုင်ရှင်ကို မတွေ့ပါ။'],INVALID_TRANSFER_AMOUNT:[400,'Transfer amount မမှန်ပါ။'],TRANSFER_SELF:[400,'ကိုယ့် Wallet ကိုယ် ပြန်လွှဲလို့မရပါ။'],INSUFFICIENT:[400,'Balance မလုံလောက်ပါ။']};const [status,message]=map[code]||[500,'Wallet server error ဖြစ်နေပါတယ်။'];return res.status(status).json({ok:false,error:code,message});}
function historyItem(x,userId){const mine=String(x.fromUserId)===String(userId);const other=mine?x.toUserId:x.fromUserId;return {id:String(x._id||''),direction:mine?'sent':'received',amount:Number(x.amount||0),otherUserId:other?String(other):null,source:x.meta?.source||null,createdAt:x.createdAt};}
async function notifyRecipient(bot,result,senderUserId){if(!bot||!result?.recipientUserId)return;try{const sender=await getUser(senderUserId);const senderName=displayName(sender);const when=new Date(result.transferredAt||Date.now()).toLocaleString('en-GB',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false,timeZone:'Asia/Bangkok'});const text=['💸 <b>Balance Received</b>','',`You have received <b>$${Number(result.amount||0).toLocaleString('en-US')}</b> from <b>${escHtml(senderName)}</b>.`,'',`Sender: <code>${escHtml(result.senderWalletId||senderUserId)}</code>`,`Recipient ID: <code>${escHtml(result.walletId||'—')}</code>`,`Time: <code>${escHtml(when)}</code>`,'','Your balance has been updated successfully.'].join('\n');await bot.telegram.sendMessage(Number(result.recipientUserId),text,{parse_mode:'HTML'});}catch(err){console.warn('[WALLET_TRANSFER_DM_FAILED]',err?.message||err);}}
module.exports=function registerWalletRoutes(app,options={}){const bot=options.bot||null;
 app.post('/api/mini/wallet',auth,async(req,res)=>{try{await ensureUser(tgUser(req.telegramUser));return res.json({ok:true,wallet:await getWallet(req.telegramUser.id)});}catch(err){return sendError(res,err);}});
 app.post('/api/mini/wallet/lookup',auth,async(req,res)=>{try{return res.json({ok:true,wallet:await lookupWallet(req.body?.walletId)});}catch(err){return sendError(res,err);}});
 app.post('/api/mini/wallet/transfer',auth,async(req,res)=>{try{await ensureUser(tgUser(req.telegramUser));const result=await transferByWallet(req.telegramUser.id,req.body?.walletId,req.body?.amount);await notifyRecipient(bot,result,req.telegramUser.id);return res.json({ok:true,...result});}catch(err){return sendError(res,err);}});
 app.post('/api/mini/wallet/transfers',auth,async(req,res)=>{try{await ensureUser(tgUser(req.telegramUser));const limit=Math.min(100,Math.max(1,Number(req.body?.limit||50)));const docs=await txModel.collection().find({type:'gift','meta.source':'mini_wallet',$or:[{fromUserId:req.telegramUser.id},{toUserId:req.telegramUser.id}]}).sort({createdAt:-1}).limit(limit).toArray();return res.json({ok:true,items:docs.map(x=>historyItem(x,req.telegramUser.id))});}catch(err){return sendError(res,err);}});
};
